### ISSUE TITLE
Planning for v8

### ISSUE THREAD

**Issue by MartijnOud** [123lens/bol-retailer-api#94]
Hi guys! It seems another year has passed, meaning another forced api update.

Do you have any plans to support the v7 or v8 version of the api? I'm still on v6 which is being EOL'd 2023-05-01.

I've tried the latest release but that just gave me a generic "The supplied accept header media type is not supported. : Bad Request (400)" error.

**Comment by avido** [comment]
Hi Martijn,

Did you try to 8.0.2 version?

Cheers

**Comment by MartijnOud** [comment]
Yes exactly.

![Screenshot 2023-02-27 at 21 37 36](https://user-images.githubusercontent.com/1292436/221680111-3cd0b47a-6d64-4068-84e5-d27831462988.png)

I'll try a different server tomorrow and try to dig for a better error message. So it's probably on my end, you have v8 running?

**Comment by avido** [comment]
So it's probably on my end, you have v8 running?
> Yes, we do 

Did you get the error message on a specific endpoint?

**Comment by MartijnOud** [comment]
I tried the `shipOrderItem` function, but didn't test very thoroughly because I thought it was still in development. I'll debug further myself and get back to you with a proper report :)

**Comment by avido** [comment]
> I tried the `shipOrderItem` function, but didn't test very thoroughly because I thought it was still in development. I'll debug further myself and get back to you with a proper report :)

👍🏻 Feel free to drop a PR
