### ISSUE TITLE
waitUntilComplete wrong accept header

### ISSUE THREAD

**Issue by MartijnOud** [123lens/bol-retailer-api#95]
I'm updating from 6.0.0 to 8.0.2 but the api keeps throwing errors when I run `$clientBol->status->waitUntilComplete($shipment->processStatusId)`. It throws a generic "The supplied accept header media type is not supported. : Bad Request (400)". Only this part seems to be broken, getting new orders and generating the `$shipment->processStatusId` value works.

I've narrowed it down to the function in `src/Endpoints/Status.php`, the getById() function is where it fails. So I tried hardcoding the same Accept header `application/vnd.retailer.v6+json` that performHttpCall() expects, but that didn't change anything.

Is the waitUntilComplete() function changed? Or do you have any idea why the api is rejecting my response?

**Comment by avido** [comment]
@MartijnOud i'm having trouble to reproduce your issue. The v6 headers are not used in the current `v8` release. 
Are you sure you're on the right version?

**Comment by avido** [comment]
@MartijnOud sorry my bad should have got this sooner, but status functionality has been moved.

You should use the `SharedClient()`

**Comment by MartijnOud** [comment]
Do you maybe have an example of how this is supposed to work? I'm still struggling to get this working again.

**Comment by avido** [comment]
> Do you maybe have an example of how this is supposed to work? I'm still struggling to get this working again.

See : https://github.com/123lens/bol-retailer-api/blob/v8/tests/Feature/Endpoints/SharedApi/StatusTest.php

**Comment by MartijnOud** [comment]
I'm sorry, I still don't understand. I did find that and I've tried most variants of:

```
$status = $clientBol->SharedClient->waitUntilComplete($shipment->processStatusId, 10, 5);
$status = $clientBol->SharedClient->status->waitUntilComplete($shipment->processStatusId, 10, 5);
```

But I'm probably missing something really obvious. My current set-up looks something like this:

```
$clientBol = new \Budgetlens\BolRetailerApi\Client();
$shipment = $clientBol->orders->shipOrderItem($product->id_bolcom, null, null, $transport);
$status = $clientBol->status->waitUntilComplete($shipment->processStatusId, 10, 5);
```

**Comment by avido** [comment]
> I'm sorry, I still don't understand. I did find that and I've tried most variants of:
> 
> ```
> $status = $clientBol->SharedClient->waitUntilComplete($shipment->processStatusId, 10, 5);
> $status = $clientBol->SharedClient->status->waitUntilComplete($shipment->processStatusId, 10, 5);
> ```
> 
> But I'm probably missing something really obvious. My current set-up looks something like this:
> 
> ```
> $clientBol = new \Budgetlens\BolRetailerApi\Client();
> $shipment = $clientBol->orders->shipOrderItem($product->id_bolcom, null, null, $transport);
> $status = $clientBol->status->waitUntilComplete($shipment->processStatusId, 10, 5);
> ```

The SharedClient is a different client. So per your example

```php
$clientBol = new \Budgetlens\BolRetailerApi\Client($config);
$sharedClient = new \Budgetlens\BolRetailerApi\SharedClient($config);
$shipment = $clientBol->orders->shipOrderItem($product->id_bolcom, null, null, $transport);
$status = $sharedClient->status->waitUntilComplete($shipment->processStatusId, 10, 5);
```

**Comment by MartijnOud** [comment]
Thank you! This is exactly what I needed 😁
